name: Trigger Deploy to Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: swlacy/swlacycom
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$GITHUB_REPO/dispatches \
            -d '{"event_type": "trigger_action", "client_payload": {}}'
